# Run evrything ;)

version: "2"

services:
  anaconda3:
    image: continuumio/anaconda3
    container_name: anaconda3
    command: /opt/conda/bin/jupyter notebook --notebook-dir=/workdir --ip='*' --port=8888 --allow-root --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./src/poc:/workdir
      - ./data:/data
  
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data/

  dbadmin:
    image: fenglc/pgadmin4
    container_name: dbadmin
    depends_on:
      - db
    ports:
      - 5050:5050
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin    

volumes:
  pgdata:
    external: true